### ISSUE TITLE
ValueError: Unknown activation function:leaky_relu

### ISSUE THREAD

**Issue by resace3** [BBQuercus/deepBlink#107]
**Describe the bug**
I am trying to test out the neural network you have with the fixed.h5 file from figshare and a random jpg I found on the internet (https://ih1.redbubble.net/image.905467034.3030/flat,750x1000,075,f.jpg)

**To Reproduce**
1. conda env create -f environment.yml  
2. Download the jpg I showed
3. Download the fixed.h5 file from figshare
4. deepblink fixed.h5 test.jpg

**Expected behavior**
Run Dot Detection

**Screenshots**
(deepblink) [nrezaee@login1 deepblink]$ deepblink -v fixed.h5 test2.jpg 
Traceback (most recent call last):
  File "/home/nrezaee/miniconda3/bin/deepblink", line 8, in <module>
    sys.exit(main())
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/deepblink/cli.py", line 240, in main
    model = tf.keras.models.load_model(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 177, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 105, in deserialize
    return deserialize_keras_object(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 369, in deserialize_keras_object
    return cls.from_config(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 986, in from_config
    input_tensors, output_tensors, created_layers = reconstruct_from_config(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 2019, in reconstruct_from_config
    process_layer(layer_data)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py", line 2001, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 105, in deserialize
    return deserialize_keras_object(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 375, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 655, in from_config
    return cls(**config)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 417, in __init__
    self.activation = activations.get(activation)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/activations.py", line 460, in get
    return deserialize(identifier)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/activations.py", line 418, in deserialize
    return deserialize_keras_object(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 392, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
ValueError: Unknown activation function:leaky_relu

**Desktop (please complete the following information):**
 - OS: CentOS Linux 7

**Additional context**
This project seems really cool and useful to the research in my lab!

**Comment by resace3** [comment]
The error seems to be from loading the model. 

Once I added the leaky relu section in

`def main():
    """Entrypoint for the CLI."""
    args = _parse_args()

    # Model import
    fname_model = os.path.abspath(args.MODEL.name)
    model = tf.keras.models.load_model(
        fname_model,
        custom_objects={
            "f1_score": f1_score,
            "rmse": rmse,
            "combined_bce_rmse": combined_bce_rmse,
            "combined_f1_rmse": combined_f1_rmse,
            'leaky_relu': tf.nn.leaky_relu
        },
    )`

I got a new error that is very similar the previous one

```
(deepblink) [nrezaee@login1 deepblink]$ deepblink -v fixed.h5 test2.jpg 
2020-11-11 20:28:48.638064: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
Traceback (most recent call last):
  File "/home/nrezaee/miniconda3/bin/deepblink", line 8, in <module>
    sys.exit(main())
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/deepblink/cli.py", line 240, in main
    model = tf.keras.models.load_model(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 193, in load_model_from_hdf5
    model.compile(**saving_utils.compile_args_from_training_config(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 215, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 255, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/losses.py", line 1831, in deserialize
    return deserialize_keras_object(
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 392, in deserialize_keras_object
    raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
ValueError: Unknown loss function:combined_dice_rmse
```

Do you think this is because the custom_objects for the model are not being loaded correctly?

**Comment by BBQuercus** [comment]
Hi, thanks for using deepBlink. It is indeed because of the custom_objects. The models use losses / activation functions that are part of our library.

Unfortunately, the models figshare don't yet align with the latest version on pypi. We planned to release an up-to-date version today or tomorrow. I'll update you so you can see if things work. As current workaround you can use:

```python
model = tf.keras.models.load_model(
        fname,
        custom_objects={
            "combined_bce_rmse": deepblink.losses.combined_bce_rmse,
            "combined_dice_rmse": deepblink.losses.combined_dice_rmse,
            "combined_f1_rmse": deepblink.losses.combined_f1_rmse,
            "f1_score": deepblink.losses.f1_score,
            "leaky_relu": tf.nn.leaky_relu,
            "rmse": deepblink.losses.rmse,
        },
    )
```

or use ```deepblink.io.load_model``` from the current master branch.

**Comment by resace3** [comment]
Thanks for the quick reply Bastian!

With the update you put in last night, I get 

`(deepblink) [nrezaee@login1 deepblink]$ deepblink -v fixed.h5 test2.jpg                                                               
Traceback (most recent call last):
  File "/home/nrezaee/miniconda3/bin/deepblink", line 8, in <module>
    sys.exit(main())
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/deepblink/cli.py", line 243, in main
    "combined_bce_rmse": deepblink.losses.combined_bce_rmse,
NameError: name 'deepblink' is not defined`

It just ended up being an error with the imports it looks like. I changed them to 

```
from .data import get_coordinate_list

from .data import next_power

from .data import normalize_image

from .io import basename

from .io import load_image

from .losses import combined_bce_rmse as combined_bce_rmse

from .losses import combined_f1_rmse as combined_f1_rmse

from .losses import combined_dice_rmse as combined_dice_rmse

from .losses import f1_score as f1_score

from .losses import rmse as rmse
```

but I get 

`(deepblink) [nrezaee@login1 deepblink]$ deepblink -v fixed.h5 test2.jpg 
Traceback (most recent call last):
  File "/home/nrezaee/miniconda3/bin/deepblink", line 5, in <module>
    from deepblink.cli import main
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/deepblink/__init__.py", line 21, in <module>
    from . import cli
  File "/home/nrezaee/miniconda3/lib/python3.8/site-packages/deepblink/cli.py", line 48, in <module>
    from .losses import combined_dice_rmse as combined_dice_rmse
ImportError: cannot import name 'combined_dice_rmse' from 'deepblink.losses' (/home/nrezaee/miniconda3/lib/python3.8/site-packages/deepblink/losses.py)`

It seems like `combined_dice_rmse` is not defined yet.

**Comment by resace3** [comment]
This seems like a very cool project! I am looking forward to getting the newer models.

Also, are you able to start allowing users to train their own models on deepblink. I read the documentation but when I run `deepblink -h`, I do not see the option yet.

**Comment by BBQuercus** [comment]
I think you might be on a older version. Have you tried creating a new Conda environment (python 3.6-3.8 are supported) and then `pip install deepblink` (latest version is 0.0.7)?

In that you should have most things you need. You can also use the CLI to download the models directly with `deepblink download --list` / `deepblink download -i MODEL`. With the models from there custom_objects shouldn't be a problem anymore.

We also support custom training through the CLI, we're finalising things so there might be some bugs here and there but feel free to look around.

**Comment by resace3** [comment]
I have it working now. I am going to try and train it on some data this weekend and can give you some feedback if you would like.

Also, I know this is an early project but am curious do you plan on adding more functionalities?

If you are looking on something extra to add, being able to predict and output an intensity relative to the illumination around the dot would be great add on. Right now I can trace the location of the dot back to the original image and get the intensity but even with illumination correction the image does not seem to give the evenly distributed brightness I would want and this seems to be a big problem in the field in general. If you were able to add that to DeepBlink, it would get a lot of popularity! but then again it depends on what direction you want to go in and what your goals are.

**Comment by BBQuercus** [comment]
We plan to make it as openly accessible to anyone wanting to detect spots (FISH / live cell / bacterial colonies etc.). So feedback would be greatly appreciated!

We already have something to compute the intensity. In `deepblink predict` you can pass the optional `-r / --radius` flag which will add an intensity column to the output file. Note that a radius of zero = central pixel only.

We will most likely add more functionalities later on. However, we implemented most of the core things and are now waiting for users to start using it and providing feedback.

**Comment by resace3** [comment]
Sweet! Well it looks amazing Bastian! 

I hope to give you some feedback by Monday!

**Comment by resace3** [comment]
Sorry I have not gotten back to you. My team has decided to move on with some other simpler dot detection techniques for now but we may come back to this to improve our dot detection.

Have you heard of ilastik (https://www.ilastik.org/). If you were able to contact the makers of ilastik and integrate it into their UI, people would be much more likely to use it, but that would be a monumental task, but many people would use it since ilastik is such a wide known name in microscopy images. 

Good Luck with this project!
