### ISSUE TITLE
Error when using both probability and radius parameters

### ISSUE THREAD

**Issue by nickeener** [BBQuercus/deepBlink#140]
Hi, thanks for making this super useful tool! Just wanted to let you know I encountered a minor bug that occurs when you try to use both the probability and radius parameters simultaneously when predicting (ie: `deepblink predict --model model.h5 --input img.tiff -r 1 -p 0.9`). Running using both parameters causes it to throw the following error:

> Traceback (most recent call last):
File "/mnt/envs/dev-nkeener/bin/deepblink", line 33, in
sys.exit(load_entry_point('deepblink==0.1.3', 'console_scripts', 'deepblink')())
File "/mnt/envs/dev-nkeener/lib/python3.7/site-packages/deepblink/cli/_main.py", line 115, in main
handler()
File "/mnt/envs/dev-nkeener/lib/python3.7/site-packages/deepblink/cli/_predict.py", line 71, in call
self.predict_adaptive(fname_in, image)
File "/mnt/envs/dev-nkeener/lib/python3.7/site-packages/deepblink/cli/_predict.py", line 193, in predict_adaptive
curr_df = self.predict_single(single_image, pixel_size)
File "/mnt/envs/dev-nkeener/lib/python3.7/site-packages/deepblink/cli/_predict.py", line 165, in predict_single
df["i"] = get_intensities(image, coords, self.radius)
File "/mnt/envs/dev-nkeener/lib/python3.7/site-packages/deepblink/inference.py", line 105, in get_intensities
for r, c in coordinate_list:
ValueError: too many values to unpack (expected 2)

This is because `coordinate_list` in the `get_intensities()` function in inference.py can have either 2 or 3 columns depending on if you used the probability parameter so that function will need to be adjusted to handle the variable number of columns.

**Comment by BBQuercus** [comment]
Hey. Thanks for letting us know! I was able to reproduce the error. We'll try to get it fixed by early next week.

**Comment by nickeener** [comment]
Thank you!

**Comment by BBQuercus** [comment]
PR #141 should have solved the issue above. To use it before we publish the next official release just make sure to clone the repository and `pip install -e .` instead of using the version on pypi.
